local RunService = game:GetService("RunService")
local ServerScriptService = game:GetService("ServerScriptService")
local TargetNearbySensor = require(ServerScriptService.Server.ai.sensing.TargetNearbySensor)
local SuspicionManagement = require(ServerScriptService.Server.ai.suspicion.SuspicionManagement)
local TriggerZone = require(ServerScriptService.Server.zone.TriggerZone)

local rig: Model = workspace:WaitForChild("Rig")
local currentSusMan = SuspicionManagement.new()
local currentNearbySensor = TargetNearbySensor.new(20)
local currentTriggerZone = TriggerZone.fromPart(workspace:WaitForChild("Zone1"))

RunService.PreAnimation:Connect(function(deltaTime)
	currentTriggerZone:update()
	currentNearbySensor:update(rig.PrimaryPart.Position, currentTriggerZone:getPlayersInZone())
	currentSusMan:update(deltaTime, currentNearbySensor.detectedTargets)
end)