--!strict

export type PlayerStatus =
	"MINOR_TRESPASSING"
	| "MAJOR_TRESPASSING"
	| "MINOR_SUSPICIOUS"
	| "CRIMINAL_SUSPICIOUS"
	| "DISGUISED"
	| "ARMED"

local StatusPriority: { PlayerStatus } = {
	"MINOR_TRESPASSING",
	"MAJOR_TRESPASSING",
	"MINOR_SUSPICIOUS",
	"CRIMINAL_SUSPICIOUS",
	"DISGUISED",
	"ARMED"
}

local Statuses = {
	MINOR_TRESPASSING = "MINOR_TRESPASSING",
	MAJOR_TRESPASSING = "MAJOR_TRESPASSING",
	MINOR_SUSPICIOUS = "MINOR_SUSPICIOUS",
	CRIMINAL_SUSPICIOUS = "CRIMINAL_SUSPICIOUS",
	DISGUISED = "DISGUISED",
	ARMED = "ARMED"
}

local t = {
	STATUS_BY_PRIORITY = StatusPriority,
	PLAYER_STATUSES = Statuses
}

return t :: typeof(t)