--!strict

export type PlayerStatus =
	"MINOR_TRESPASSING"
	| "MAJOR_TRESPASSING"
	| "MINOR_SUSPICIOUS"
	| "CRIMINAL_SUSPICIOUS"
	| "DISGUISED"
	| "ARMED"

local StatusPriority: { PlayerStatus } = {
	"MINOR_TRESPASSING",
	"MAJOR_TRESPASSING",
	"MINOR_SUSPICIOUS",
	"CRIMINAL_SUSPICIOUS",
	"DISGUISED",
	"ARMED"
}

local StatusesWeight: { [PlayerStatus]: number } = {
	MINOR_TRESPASSING = 3.5,
	MAJOR_TRESPASSING = 4.0,
	MINOR_SUSPICIOUS = 2.0,
	CRIMINAL_SUSPICIOUS = 5.0,
	DISGUISED = 1.5,
	ARMED = 10
}

local Statuses = {
	MINOR_TRESPASSING = "MINOR_TRESPASSING",
	MAJOR_TRESPASSING = "MAJOR_TRESPASSING",
	MINOR_SUSPICIOUS = "MINOR_SUSPICIOUS",
	CRIMINAL_SUSPICIOUS = "CRIMINAL_SUSPICIOUS",
	DISGUISED = "DISGUISED",
	ARMED = "ARMED"
}

local t = {
	STATUS_BY_PRIORITY = StatusPriority,
	STATUS_BY_WEIGHT = StatusesWeight,
	PLAYER_STATUSES = Statuses,
}

return t :: typeof(t)